### ISSUE TITLE
/objc-internal.h:127:27: error: expected function body after function declarator     __WATCHOS_UNAVAILABLE __BRIDGEOS_UNAVAILABLE;

### ISSUE THREAD

**Issue by yidahis** [DeveloperErenLiu/RuntimeAnalyze#2]
/objc-internal.h:127:27: error: expected function body after function declarator
    __WATCHOS_UNAVAILABLE __BRIDGEOS_UNAVAILABLE;
打开一运行就这样，XCode 10.1

**Comment by xinxi053** [comment]
删了就行了，没什么用。

**Comment by DeveloperErenLiu** [comment]
> /objc-internal.h:127:27: error: expected function body after function declarator
> __WATCHOS_UNAVAILABLE __BRIDGEOS_UNAVAILABLE;
> 打开一运行就这样，XCode 10.1

**Comment by DeveloperErenLiu** [comment]
这个可能和新版本Xcode有关系，我用Xcode9.4.1跑代码，发现有崩溃的问题，正在解决。

**Comment by DeveloperErenLiu** [comment]
@xinxi053 说的对，直接删掉即可，不会影响代码执行。就是用来修饰objc_isAuto函数的，没什么用
